apiVersion: apps/v1
kind: Deployment
metadata:
  name: recorder-deployment
  labels:
    app: recorder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recorder
  template:
    metadata:
      labels:
        app: recorder
    spec:
      containers:
      - name: recorder
        image: chukwuka1488/recorder-service:3.0
        ports:
        - containerPort: 7000