apiVersion: v1
kind: Service
metadata:
  name: recorder-service
spec:
  type: NodePort
  selector:
    app: recorder
  ports:
    - protocol: TCP
      port: 7070
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 7100
